### ISSUE TITLE
clarify PSA scope and applicability

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-psa-token#119]
Eliot:

> I would like some statement, without it turning into an advertisement, about who and what PSA is.  Is this really just an ARM initiative or is it broader?  Some clarity would help, so that implementors understand applicability.

**Comment by SimonFrost-Arm** [comment]
I don't have exact text yet, but perhaps the best approach is to paraphrase https://www.psacertified.org/what-is-psa-certified/founding-members, something along the lines of

PSA Certified represents an independent collaborative effort maintained by companies from multiple sectors including evaluation laboratories, semiconductor IP and security consultancy. For more details see [link above]

WDYT?

**Comment by thomas-fossati** [comment]
> I don't have exact text yet, but perhaps the best approach is to paraphrase https://www.psacertified.org/what-is-psa-certified/founding-members, something along the lines of
> 
> PSA Certified represents an independent collaborative effort maintained by companies from multiple sectors including evaluation laboratories, semiconductor IP and security consultancy. For more details see [link above]
> 
> WDYT?

Looks great!  The only thing is I wouldn't know how to plug it into the current Abstract :-)

**Comment by thomas-fossati** [comment]
Eliot suggestion:

> Just state the nature and purpose of the organization.  An example might be, _"a consortium of chip manufacturers who have developed a profile for the purpose of ..."_
