### ISSUE TITLE
The EAT media type for `PSA_IOT_PROFILE_1` is incorrect

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-psa-token#142]
`PSA_IOT_PROFILE_1` parses as a URI, but not as not an absolute URI.  

While there is no explicit requirement in EAT to make it absolute, the following observations hold:

1. The OID form is required to be absolute, and
1. The idea is to make the profile identifier unique (without an
explicit registration procedure),

So I think _the spirit_ is to have absolute URIs there.

We'll either drop the `PSA_IOT_PROFILE_1` media type completely or make a separate media type registration for it.

**Comment by mathias-arm** [comment]
My suggestion would be to change `PSA_IOT_PROFILE_1 ` to something like `application/eat+cwt;eat_profile=tag:psacertified.org,2019:psa#tfm`
(or `application/eat+cwt;eat_profile=tag:psacertified.org,2019:legacy#tfm`)
and document the mapping to older implementation using `PSA_IOT_PROFILE_1 ` in their token.

**Comment by SimonFrost-Arm** [comment]
I think Mathias' scheme works - most consistent with the new entry.
