### ISSUE TITLE
Crypto interoperability

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-psa-token#21]
I would specify a set of crypto algorithms that the Verifier must implement (e.g., ES256, ES384, AES-CBC-MAC-256//64...)... The Verifier must implement them all, the Attester doesn't have to implement all, just one.

A profile should lock everything down to have guaranteed interoperability.

**Comment by adrianlshaw** [comment]
Makes sense to me. So far this draft is just leaning on what is defined in the COSE RFC, but we ought to lock it down, as you say. Thanks for the suggestion.
