### ISSUE TITLE
Verification key identification

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-psa-token#22]
The Instance ID description mostly says it, but I think it would be good to add a small section on how the Verifier gets the verification key and how it constitutes and endorsement of the Attester.

Something like, "the Verifier must obtain verification keys out of band from the Endorser. The Verifier selects the verification key to use based on the Instance ID/UEID". 

This should also address keys for Mac0. I assume Instance ID/UEID will also be used for Mac0.

It should probably say that for PSA Token, the distribution and availability of a Verification key constitutes and Endorsement of the Attester.

I kind of think it is OK for a profile document to go into full detail of the key lifecycle and distribution, maybe even defining the format of an Endorsement. Maybe it is out of scope of the RATS WG, but to have an interoperable end-end system some of this probably needs to be filled in.

**Comment by thomas-fossati** [comment]
> I kind of think it is OK for a profile document to go into full detail of the key lifecycle and distribution, maybe even defining the format of an Endorsement. Maybe it is out of scope of the RATS WG, but to have an interoperable end-end system some of this probably needs to be filled in.

This is fundamental information for closing the verification loop.  However, I don't think the token draft is the place for this discussion.  Instead, we are building the supply-chain -> Verifier protocol as a profile of the DICE endorsements [here](https://github.com/thomas-fossati/draft-psa-endorsements).
