### ISSUE TITLE
What does Implementation ID really identify?

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-psa-token#23]
I can't tell if it is:
 -- like a serial number that is different in every physical device
 -- like a SW version number
 -- like a class of types of attester implementations ... a model number
 -- something else?

I try to describe the space in which any ID operates so the reader knows what the identifier is trying to "uniquely identify". (pretty much all identifiers aim to *uniquely* identify, so uniquely isn't a useful word here").

**Comment by adrianlshaw** [comment]
The implementation ID identifies the implementation of the PSA Root of Trust. If the RoT is pure hardware, then it could be, for example, an EAN. If the RoT is a combination of hardware and firmware, then it might be some number chosen by an Endorser in a public database. Ultimately, whatever form it takes, it has to be used by a Verifier to look up the certification status of that RoT.

If a chip gets revved and/or its firmware gets updated, then I believe it is up to both the vendor and the certification scheme whether a new implementation ID should be used.

So in some cases, it could be a model number, in other cases it could be just an index into a database. Supply chains are way too varied to be able to suggest something in particular.

>  -- like a serial number that is different in every physical device

We have a separate claim called Instance ID, which is different for every physical device. 

Hope that makes some sense.

**Comment by laurencelundblade** [comment]
Yes, that makes sense and I understand now. It would be good to update the document so the readers can understand too.

**Comment by thomas-fossati** [comment]
Fixed in #35
