### ISSUE TITLE
Claim key standardization

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-psa-token#24]
Will you standardize all the claim keys and stop using one out of the private space? If so you might say so and add an IANA section for it.

**Comment by thomas-fossati** [comment]
> Will you standardize all the claim keys and stop using one out of the private space?

No, the rationale we use is:
* if claim is standardised in EAT, use it;
* if not, grab a codepoint from the private space: the value of the (standard) profile claim will provide the unambiguous domain of interpretation for it -- and its (private and non-private) siblings.

That was the reason for pestering you about pre-allocating the profile claim :-)

**Comment by laurencelundblade** [comment]
This surprises me a bit. I personally would register them in the Specification Required space.

I know this creates a backwards compatibility problem during early deployments, but that isn't too hard to solve. ctoken and xclaim handle it fine now.

A potential worse problem is that the meaning of a claim key is conditional on the profile claim. For example what if the XYZ token used -75001 to mean something completely different from PSA. This makes it hard for general SW like ctoken and xclaim to support.  The odds of this seems low because the space is so big, but seems worth mentioning.

Having it in the registry also helps market PSA token. 

That said, I mostly understand the approach here.
