### ISSUE TITLE
UCCS and TLS-based security

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-psa-token#26]
Can PSA token be used with UCCS and TLS-based security? If so this should be described.

**Comment by thomas-fossati** [comment]
> Can PSA token be used with UCCS

Answering this question would require us to do some serious security analysis to show under which circumstances using a UCCS PSA token is secure.  At this point in time we are not seeing any push for this feature, therefore we are going to defer.

> and TLS-based security?

Hannes and Mathias have put forward [a proposal](https://tools.ietf.org/html/draft-tschofenig-tls-cwt-02) that would work with any CWT, including the PSA token.  The draft is now expired and I'm not sure if there's any plans to revive it.
