### ISSUE TITLE
boot seed is in EAT and PSA can reference its definition

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-psa-token#29]
I forgot I'd put boot seed in EAT. I think it belongs there because it is quite generic and certainly not specific to PSA.

The section number for boot seed in EAT is wrong and thus harder to notice. Will be fixed in next EAT draft.

**Comment by thomas-fossati** [comment]
You mean you wanted to pre-register `boot-seed`?  If yes, depending on when TF-M catches up with the draft, this may be too late.  I will keep this issue open to see if the stars align!

**Comment by laurencelundblade** [comment]
No, I don't want to pre-register. I don't want to slow down the pre-reg that we have in progress now.

I want to be clear that PSA boot seed is exactly the same as EAT boot seed. When PSA mentions UEID and profile it says that they are EAT claims. boot seed should be the same.

**Comment by thomas-fossati** [comment]
> No, I don't want to pre-register. I don't want to slow down the pre-reg that we have in progress now.

Sure, makes sense.

> I want to be clear that PSA boot seed is exactly the same as EAT boot seed. When PSA mentions UEID and profile it says that they are EAT claims. boot seed should be the same.

The profile and ueid used by PSA are effectively EAT claims.  OTOH boot-seed has the same semantics and the same value format as its EAT counterpart, but the respective map keys are different, so the analogy is not full.  That said, we might say that (it costs nothing), but I'm failing to understand the value added?

**Comment by laurencelundblade** [comment]
Seems to me that having two claims that are exactly the same except for the claim key is confusing for the EAT ecosystem.

It adds complexity for implementations like ctoken and xclaim:
- There must be two encode methods for boot seed and the documentation has to explain to the caller when to use one or the other.
- The decoder has to recognize both claim keys and report which was used to the caller so the caller can error out if the wrong one was used
- If the decoder is really thorough, then maybe it has a PSA mode and non-PSA mode
- The users and implementors have more to think about

This probably triples the lines of code and documentation in xclaim and ctoken for boot seed.

All this because you want to lock down the claim keys now rather than wait until the standard is done? The code to manage the transition from temporary claim key to permanent claim key is not that hard and can eventually be deleted. The complexity from two claim keys for the same thing is permanent.

**Comment by thomas-fossati** [comment]
We are using all the EAT claims that have been sent through the early allocation procedure.  Boot seed is not one of these and since we need a code point now, there seem to be no alternative than to mint one.  If we get to the IANA registry first, EAT could use the same code point.
