### ISSUE TITLE
Comment on no SW components

### ISSUE THREAD

**Issue by laurencelundblade** [thomas-fossati/draft-psa-token#37]
This is mostly an FYI. Close it when you feel informed. :-)

In my decoding implementation of SW components, the no sw components indicator adds about 25% to the implementation when counting lines of code. https://github.com/laurencelundblade/ctoken/pull/35

There are more error conditions than there would be without it. Anytime a SW component is fetched, a check must be made for the no SW components indicator and made sure it is the right type and content. Then there is the error when both the no SW component indicator is present along with the SW components and vice versa.

It adds three test cases to the test vector. https://github.com/laurencelundblade/EAT-test-vectors/tree/main/src/psa_swcomponents

Took me about a day's work in total to get it all implemented, debugged and tested.

The extra stuff is all on the decode side. Nothing hard on the encode side.

I may not have all the context, but it seems like a net loss in value and not a common thing in protocol design.

**Comment by thomas-fossati** [comment]
I personally agree with the analysis (it's been my experience too while implementing the verifier side of this).  I am not sure we are in a position to make this change now though.

**Comment by adrianlshaw** [comment]
Can we at least mark it as deprecated so people can avoid using it?

**Comment by SimonFrost-Arm** [comment]
When we first defined the PSA claim set, there was a stipulation that it should be able support devices without Secure & Measured boot, hence the Software Components claim was optional and the NoSWComponents claim allowed certainty that this was a deliberate act. Reading the current PSA SM, secure & measured boot is required so we can make the software component claim mandatory and deprecate the NoSWComponents claim.

**Comment by thomas-fossati** [comment]
Reopening this given the good news in https://github.com/thomas-fossati/draft-psa-token/issues/37#issuecomment-1059238120
