### ISSUE TITLE
clarify what goes into the measurement description

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-psa-token#41]
IIRC this was supposed to contain a textual description of the hash algorithm used for the measurement (e.g., https://www.iana.org/assignments/hash-function-text-names/hash-function-text-names.xhtml).

[Adrian](@adrianlshaw) can you please confirm -- or refute :-) ?

**Comment by adrianlshaw** [comment]
Sure thing! No, it was not meant for an algorithm identifier. The intent of this claim is to simply give the verifier more information about the measurement. Think of it as a long form description that goes beyond what "Measurement Type" implies. It is a free form string, so it can be anything, but a few examples come to mind:
* it could disambiguate whether the measurement is code or configuration data, if these items are loaded separately 
* it could could include the start and end addresses of the measured image in flash/RAM. A verifier can use this information to recompute the digest, if they choose to do so. 
* it could contain the actual data of what is measured, if it small enough, such as a configuration file or bitmap. The verifier can then create a digest of the configuration data and compare against the measurement digest in the token. 

In practice, keeping the token size down is what matters for a lot of IoT devices, so this claim has never been used in anger. If you are familiar with TCG, a similar example is the TCG Event Log, which contains a lot of event data to help the verifier recompute and compare digests. The lack of structure within this definition makes it difficult for a verifier to use this in an interoperable way.  

That all said, I think it very valuable to have a separate subclaim (whatever the term may be) that describes the hash algorithm in use for each digest. This would improve the token. I think the IANA reference you have would be perfect.

**Comment by adrianlshaw** [comment]
I corrected a few typos in my response

**Comment by thomas-fossati** [comment]
hi Adrian, thanks for fixing my bad memory!

However, it looks like the original intent got lost in the implementation: for example, [MCUBoot](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.3.1/mcuboot/design.html#measured-boot-and-data-sharing) seems to use the claim for _"[...] algorithm used to calculate the measurement value"_, a choice that was mirrored in [TF-M](https://review.trustedfirmware.org/plugins/gitiles/TF-M/trusted-firmware-m/+/27a61454e3e4855a6b4b6bd1119150a4f502550a/bl2/src/boot_record.c#57).  So, I am not exactly sure what to do with the claim description now :-)

**Comment by thomas-fossati** [comment]
I spoke to Tamas and he confirmed it's currently a text string (e.g., "SHA256", "SHA512").

I also asked whether he saw any trouble standardising on https://www.iana.org/assignments/hash-function-text-names/hash-function-text-names.xhtml so to have a single, unambiguous way to encode the string and he was positive.

I am going to draft a PR based on this discussion shortly.
