### ISSUE TITLE
Update psa-arch-tests

### ISSUE THREAD

**Issue by adrianlshaw** [thomas-fossati/draft-psa-token#49]
Not sure if this is the right place to open this but I think it's worth tracking somewhere. Once the new claim numbers are finalized, [psa-arch-tests ](https://github.com/ARM-software/psa-arch-tests) should be updated to check for the new numbers and possibly other minor changes like the algorithm type in Measurement Description.

**Comment by thomas-fossati** [comment]
Good idea.  Noting that this should trickle down to TF-M as well.  Before that we need confirmation from IANA about the proposed numbers.  @hannestschofenig: what do we need to do in order to start the IANA review?

**Comment by thomas-fossati** [comment]
Re: TF-M. The implementation of the new profile (including the registered code-points) is done: see [this message](https://lists.trustedfirmware.org/archives/list/tf-m@lists.trustedfirmware.org/message/FHOQ42572LDERDV3XK2X42OWRAP6IL5W/) to the tf-m mailing list.

**Comment by thomas-fossati** [comment]
@adrianlshaw I _think_ this issue is superseded by https://github.com/ARM-software/psa-api/issues/7 . Could you please confirm?

**Comment by adrianlshaw** [comment]
Yes it does.

**Comment by thomas-fossati** [comment]
> Yes it does.

cool, I'll close this one then.
