### ISSUE TITLE
what we mean by "Initial" in initial attestation service"?

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-psa-token#57]
Some people may ask what we mean by "Initial attestation service". Maybe it's worth an extra sentence. The closest concept is an Initial DevID (IDevID) but also very restricted.

**Comment by thomas-fossati** [comment]
@adrianlshaw can you suggest some text for this?

**Comment by thomas-fossati** [comment]
Not sure, just wondering: apart from the temporal dimension (i.e., boot-time only), is there also a spatial argument here? I.e., "initial" referring to the first few layers of the chain of trust rather than the whole extent of the running SW.

**Comment by adrianlshaw** [comment]
I'll open a PR
