### ISSUE TITLE
format of certification reference

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-psa-token#58]
The Certificate Number of all the entries in the PSA Certified DB (at least, those I have sampled -- see for example [this SDT product](https://www.psacertified.org/products/iot-system-on-module-som-based-on-stm32f7)) has format "[0-9]{13} - [0-9]{5}" (e.g., "0716053549822 - 10023").

The Certificate Reference claim is instead just "[0-9]{13}".

Should we align the token with the PSA Certified DB?

**Comment by adrianlshaw** [comment]
Do you know what those extra 5 digits represent?

On the PSA Certified website, you can search for a product in the catalog using the 13 digit EAN, which shows that this may be unique enough. However, I assume if the same product is certified multiple times (for example with a different chip revision) then maybe the EAN stays the same and maybe the change is reflected in the extra five digits.

**Comment by thomas-fossati** [comment]
> Do you know what those extra 5 digits represent?

The [documentation](https://www.psacertified.org/app/uploads/2020/07/JSADEN011-PSA_Certified_Level_2_Step-by-Step-1.1-20200403.pdf#page=5) explains the arcane EAN-13+5 encoding.

The salient part:  _"The +5 digits enables encoding of Trusted Firmware revisions and new certification attempts. Together the EAN-13 and the +5 describe the PSA-RoT i.e. chip-type and Trusted Firmware version. The first digit of the +5 encodes the number of the successful certification attempts, or actual certifications on the same products, starting with ‘1’."_

**Comment by thomas-fossati** [comment]
cc @tamasban
