### ISSUE TITLE
add the expected AR4SI trustworthiness vector value to §11

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-psa-token#71]
Explain which PSA claims are meaningful for which AR4SI bucket (see also [Appendix B of AR4SI](https://www.ietf.org/archive/id/draft-ietf-rats-ar4si-03.html#appendix-B).)

Additionally, provide guidance on the choice of trustworthiness claims values.

**Comment by thomas-fossati** [comment]
First stab at mapping AR4SI appraisal dimensions to PSA token claims:

AR4SI TV categories | Related PSA claims
---|---
configuration | n/a (maybe IMPDEP)
executables (runtime) | software components
file system | n/a
hardware | implementation ID
instance identity | instance ID, (security lifecycle can impact the derived identity)
runtime opaque | indirectly derived from executables, hardware, instance identity
sourced data | n/a (maybe IMPDEP)
storage opaque | indirectly derived from executables, hardware, instance identity

@SimonFrost-Arm @setrofim could you please have a look?

**Comment by adrianlshaw** [comment]
> 
configuration | n/a (maybe IMPDEP)
-- | --


FWIW the Measurement Type attribute of Software Components was originally meant to represent both code measurements and configuration measurements. E.g. measurement type "PRoT" would represent the digest of the PRoT component, and "PRoT_config" would represent the measurement of its configuration. Of course, there are no normative requirements around how measurement type is used...

**Comment by thomas-fossati** [comment]
Thanks Adrian!  So, to be clear, in the table above you'd associate "software components" to AR4SI's "configuration", right?

Two things:

* We need to make sure that in §4.4.1 alongside software we also talk about configuration;
* If we want to make sure the verifier knows whether a measurement is FW/SW vs config we will need to add a way to make it apparent at the reference value provisioning interface.  This is a requirement for the PSA endorsements draft which I'll need to file.

**Comment by setrofim** [comment]
Would the security lifecycle state also contirbute to "runtime opaque"?

**Comment by adrianlshaw** [comment]
> Thanks Adrian! So, to be clear, in the table above you'd associate "software components" to AR4SI's "configuration", right?
> 
> Two things:
> 
>     * We need to make sure that in §4.4.1 alongside software we also talk about configuration;
> 
>     * If we want to make sure the verifier knows whether a measurement is FW/SW vs config we will need to add a way to make it apparent at the reference value provisioning interface.  This is a requirement for the PSA endorsements draft which I'll need to file.

Yes, and I agree with all those points. The notion of a separately measured configuration was something we had in mind but it did not make the draft because TF-M did not implement anything like it. But on richer systems like Cortex-A SoCs it's more normal to have separate config files that affect security. Let me know if you want me to review anything. Thank you!

**Comment by thomas-fossati** [comment]
> Yes, and I agree with all those points. The notion of a separately measured configuration was something we had in mind but it did not make the draft because TF-M did not implement anything like it. But on richer systems like Cortex-A SoCs it's more normal to have separate config files that affect security.

Makes sense, thanks for the historic context.

> Let me know if you want me to review anything. Thank you!

As soon as I have put together a PR I'll make sure your keen eye is summoned :-)

**Comment by thomas-fossati** [comment]
BTW, tracking the two points related to config at:

* https://github.com/thomas-fossati/draft-psa-token/issues/72 and
* https://github.com/thomas-fossati/draft-psa-endorsements/issues/34

respectively.

**Comment by SimonFrost-Arm** [comment]
> Yes, and I agree with all those points. 
+1 

> The notion of a separately measured configuration was something we had in mind but it did not make the draft because TF-M did not implement anything like it. But on richer systems like Cortex-A SoCs it's more normal to have separate config files that affect security
For completeness, TF-A has so far been taking the approach of measuring executables and config blobs in the same manner when creating evidence.
