### ISSUE TITLE
x509 and scalability

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-psa-token#80]
It is not completely unrealistic to assume a working x509 infra at the manufacturer's factory that can certify raw IAKs.

Using certified IAKs provides better scalability:
1. dropping the storage requirements on the verifier side (the factory's trust anchor would suffice), and
2. simplifying the provisioning model by removing the need to notify the verifier about each newly manufactured device.

I suggest we should allow (and maybe encourage) the x509 certified IAK to be inlined in the PSA token using the [`x5chain`](https://www.rfc-editor.org/rfc/rfc9360.html#section-2-5.4.1) COSE header.

**Comment by adrianlshaw** [comment]
Sounds good Thomas. Can ARM define the X509 certificate format that is used for the IAK cert? This would help make sure there is interoperability so verifier doesn't have to deal with lots of potential custom x509v3 extensions.

**Comment by thomas-fossati** [comment]
With @hannestschofenig a while back we did [7925](https://datatracker.ietf.org/doc/html/rfc7925), and we are refreshing it [here](https://datatracker.ietf.org/doc/draft-ietf-uta-tls13-iot-profile) for TLS 1.3.

Do you think referencing that word would be enough?

**Comment by thomas-fossati** [comment]
Adrian, thinking a bit more on your suggestion: it looks like specifying what goes in the subject / SAN of the cert (at least implementation and instance IDs) may be quite relevant.

(En passant, such device cert may also be used as an endorsement/ref-value channel.)

**Comment by adrianlshaw** [comment]
Indeed, I think instID/impID are relevant. A pointer to a place to get reference values sounds convenient - I am not sure if that should be mandatory, as you should consider what potential different delivery models there might be for reference values

**Comment by thomas-fossati** [comment]
> Indeed, I think instID/impID are relevant.

👍 

> A pointer to a place to get reference values sounds convenient

cool, I was thinking "pure inlining" but you are right, an URI from where manifests can be fetched sounds useful.  I'll try and see if TCG has already registered extensions to that purpose.

> I am not sure if that should be mandatory, as you should consider what potential different delivery models there might be for reference values

👍

**Comment by adrianlshaw** [comment]
I am not against pure inlining by the way, you might want to consider a way to support both approaches. TCG RIM in this regard supports direct and indirect.

**Comment by hannestschofenig** [comment]
No objection against mentioning the [x5chain](https://www.rfc-editor.org/rfc/rfc9360.html#section-2-5.4.1) COSE header. Existing implementations are not using it right now but that could be changed. Referencing also the TLS 1.3 cert profile could be useful, particularly since we are supposed to update it this month...

**Comment by thomas-fossati** [comment]
> Referencing also the TLS 1.3 cert profile could be useful, particularly since we are supposed to update it this month...

SGTM

**Comment by SimonFrost-Arm** [comment]
> cool, I was thinking "pure inlining" but you are right, an URI from where manifests can be fetched sounds useful. I'll try and see if TCG has already registered extensions to that purpose.
Let's keep inlining / pre-provisioning of RVs optional to support all use cases.  
Per extensions, the TCG Platform Certificate has "PlatformConfigUri attribute contains the URI where the reference integrity measurements could be obtained by the verifier."  That document has a PCR mindset but that's the closest I've seen to a general RV pointer
