### ISSUE TITLE
`eat_profile` URI structure

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-psa-token#97]
It has been pointed out that `http://arm.com/psa/2.0.0` may not be ideal as a base URI for the `eat_profile` claim:

* delegating profile definition outside the Arm corp boundary may have "branding" implications
* `http` URIs can be automatically de-referenced, causing unneeded traffic to Arm's website

One possible alternative that was briefly discussed uses [TAG URIs](https://www.rfc-editor.org/rfc/rfc4151#section-2.1).

For example, `tag:arm.com,2023:psa` or (better, more neutral from a branding perspective) `tag:psacertified.org,2023:psa`.

They would extend naturally using the "fragment" part, e.g.: `tag:arm.com,2023:psa#s+hmac`.

**Comment by SimonFrost-Arm** [comment]
LGTM: the TAG URI structure would work well & psacertified.org seems an appropriate authority. 
It will be a separate piece of work, as part of getting this value for the claim implemented, to make sure that a web search for the tag will produce a link to the actual profile document.
